// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewProject.Models;

namespace NewProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewProject.Models.JGLB", b =>
                {
                    b.Property<int>("jglbID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.Property<string>("lbName");

                    b.HasKey("jglbID");

                    b.ToTable("JGLBs");

                    b.HasData(
                        new { jglbID = 1, OperatorID = 0, Version = 0, lbName = "处方药" },
                        new { jglbID = 2, OperatorID = 0, Version = 0, lbName = "非处方药" }
                    );
                });

            modelBuilder.Entity("NewProject.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DLID");

                    b.Property<int>("LBID");

                    b.Property<string>("MedicineName");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.Property<int>("XLID");

                    b.Property<int>("ZLID");

                    b.Property<int>("bzctID");

                    b.Property<int>("jglbID");

                    b.HasKey("MedicineID");

                    b.HasIndex("DLID");

                    b.HasIndex("LBID");

                    b.HasIndex("XLID");

                    b.HasIndex("ZLID");

                    b.HasIndex("jglbID");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("NewProject.Models.PowerTeam", b =>
                {
                    b.Property<int>("powerTeamID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.Property<string>("powerTeamName");

                    b.HasKey("powerTeamID");

                    b.ToTable("powerTeams");

                    b.HasData(
                        new { powerTeamID = 1, OperatorID = 0, Version = 0, powerTeamName = "系统内置管理员" }
                    );
                });

            modelBuilder.Entity("NewProject.Models.SPBLFY", b =>
                {
                    b.Property<int>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BLFYBH");

                    b.Property<string>("BLFYMC");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("SPBH");

                    b.Property<int>("Version");

                    b.HasKey("GUID");

                    b.ToTable("SPBLFYs");
                });

            modelBuilder.Entity("NewProject.Models.SPGG", b =>
                {
                    b.Property<int>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BZDW");

                    b.Property<string>("BZSL");

                    b.Property<string>("GGBH");

                    b.Property<string>("GGMC");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("SPBH");

                    b.Property<int>("Version");

                    b.HasKey("GUID");

                    b.ToTable("SPGGs");
                });

            modelBuilder.Entity("NewProject.Models.SPJJZ", b =>
                {
                    b.Property<int>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JJZBH");

                    b.Property<string>("JJZMC");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("SPBH");

                    b.Property<int>("Version");

                    b.HasKey("GUID");

                    b.ToTable("SPJJZs");
                });

            modelBuilder.Entity("NewProject.Models.SPSYZ", b =>
                {
                    b.Property<int>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("SPBH");

                    b.Property<string>("SYZBH");

                    b.Property<string>("SYZMC");

                    b.Property<int>("Version");

                    b.HasKey("GUID");

                    b.ToTable("SPSYZs");
                });

            modelBuilder.Entity("NewProject.Models.SPTSRQYY", b =>
                {
                    b.Property<int>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<string>("RQLX");

                    b.Property<int>("SPBH");

                    b.Property<int>("Version");

                    b.Property<string>("YYSM");

                    b.HasKey("GUID");

                    b.ToTable("SPTSRQYYs");
                });

            modelBuilder.Entity("NewProject.Models.SPYBXX", b =>
                {
                    b.Property<int>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<string>("SHENG");

                    b.Property<string>("SHI");

                    b.Property<int>("SPBH");

                    b.Property<int>("Version");

                    b.Property<string>("XXLY");

                    b.Property<string>("YBBH");

                    b.Property<string>("YBLB");

                    b.Property<string>("YBZT");

                    b.HasKey("GUID");

                    b.ToTable("SPYBXXs");
                });

            modelBuilder.Entity("NewProject.Models.SPYWXHZY", b =>
                {
                    b.Property<int>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("SPBH1");

                    b.Property<int>("SPBH2");

                    b.Property<int>("Version");

                    b.Property<string>("XHZYBH");

                    b.Property<string>("ZYXG");

                    b.HasKey("GUID");

                    b.ToTable("SPYWXHZYs");
                });

            modelBuilder.Entity("NewProject.Models.SPZSJ", b =>
                {
                    b.Property<int>("SPBH")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BLFY");

                    b.Property<string>("FYYJS");

                    b.Property<string>("JGLB");

                    b.Property<string>("JX");

                    b.Property<int>("MedicineID");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<string>("PZWH");

                    b.Property<string>("SCDW");

                    b.Property<string>("SMSJJZ");

                    b.Property<string>("SMSSYZ");

                    b.Property<string>("SMSYFYL");

                    b.Property<string>("SPM");

                    b.Property<string>("TSRQYY");

                    b.Property<int>("Version");

                    b.Property<string>("XXLY");

                    b.Property<string>("YSPM");

                    b.Property<string>("YWCF");

                    b.Property<string>("YWLB");

                    b.Property<string>("YWXHZY");

                    b.HasKey("SPBH");

                    b.HasIndex("MedicineID");

                    b.ToTable("SPZSJ");
                });

            modelBuilder.Entity("NewProject.Models.subPowers", b =>
                {
                    b.Property<int>("subPowerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.Property<string>("powerUrl");

                    b.Property<string>("subPowerName");

                    b.Property<int>("supPowerID");

                    b.HasKey("subPowerID");

                    b.ToTable("subPower");

                    b.HasData(
                        new { subPowerID = 1, OperatorID = 0, Version = 0, powerUrl = "", subPowerName = "模块", supPowerID = 0 },
                        new { subPowerID = 2, OperatorID = 0, Version = 0, powerUrl = "tymk", subPowerName = "通用名库", supPowerID = 1 },
                        new { subPowerID = 3, OperatorID = 0, Version = 0, powerUrl = "", subPowerName = "系统设置", supPowerID = 1 },
                        new { subPowerID = 4, OperatorID = 0, Version = 0, powerUrl = "yhgl", subPowerName = "用户管理", supPowerID = 3 },
                        new { subPowerID = 5, OperatorID = 0, Version = 0, powerUrl = "", subPowerName = "系统设置", supPowerID = 3 },
                        new { subPowerID = 6, OperatorID = 0, Version = 0, powerUrl = "cdgl", subPowerName = "菜单管理", supPowerID = 5 },
                        new { subPowerID = 7, OperatorID = 0, Version = 0, powerUrl = "qxzgl", subPowerName = "权限组管理", supPowerID = 5 },
                        new { subPowerID = 8, OperatorID = 0, Version = 0, powerUrl = "qxcd", subPowerName = "权限菜单维护", supPowerID = 5 }
                    );
                });

            modelBuilder.Entity("NewProject.Models.TeamPowers", b =>
                {
                    b.Property<int>("TeamPowersID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.Property<int>("powerTeamID");

                    b.Property<int>("subPowerID");

                    b.HasKey("TeamPowersID");

                    b.HasIndex("powerTeamID");

                    b.HasIndex("subPowerID");

                    b.ToTable("TeamPowers");

                    b.HasData(
                        new { TeamPowersID = 1, OperatorID = 0, Version = 0, powerTeamID = 1, subPowerID = 1 },
                        new { TeamPowersID = 2, OperatorID = 0, Version = 0, powerTeamID = 1, subPowerID = 2 },
                        new { TeamPowersID = 3, OperatorID = 0, Version = 0, powerTeamID = 1, subPowerID = 3 },
                        new { TeamPowersID = 4, OperatorID = 0, Version = 0, powerTeamID = 1, subPowerID = 4 },
                        new { TeamPowersID = 5, OperatorID = 0, Version = 0, powerTeamID = 1, subPowerID = 5 },
                        new { TeamPowersID = 6, OperatorID = 0, Version = 0, powerTeamID = 1, subPowerID = 6 },
                        new { TeamPowersID = 7, OperatorID = 0, Version = 0, powerTeamID = 1, subPowerID = 7 },
                        new { TeamPowersID = 8, OperatorID = 0, Version = 0, powerTeamID = 1, subPowerID = 8 }
                    );
                });

            modelBuilder.Entity("NewProject.Models.TYMD", b =>
                {
                    b.Property<int>("DLID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DNAME");

                    b.Property<string>("GUID");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.HasKey("DLID");

                    b.ToTable("TYMD");

                    b.HasData(
                        new { DLID = 1, DNAME = "中药", OperatorID = 0, Version = 0 },
                        new { DLID = 2, DNAME = "西药", OperatorID = 0, Version = 0 },
                        new { DLID = 3, DNAME = "其他", OperatorID = 0, Version = 0 }
                    );
                });

            modelBuilder.Entity("NewProject.Models.TYMLB", b =>
                {
                    b.Property<int>("LBID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GUID");

                    b.Property<string>("LBNAME");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.HasKey("LBID");

                    b.ToTable("TYMLBs");

                    b.HasData(
                        new { LBID = 1, LBNAME = "类别1", OperatorID = 0, Version = 0 },
                        new { LBID = 2, LBNAME = "类别2", OperatorID = 0, Version = 0 },
                        new { LBID = 3, LBNAME = "类别3", OperatorID = 0, Version = 0 }
                    );
                });

            modelBuilder.Entity("NewProject.Models.TYMX", b =>
                {
                    b.Property<int>("XLID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GUID");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.Property<string>("XNAME");

                    b.Property<int>("ZLID");

                    b.HasKey("XLID");

                    b.ToTable("TYMX");

                    b.HasData(
                        new { XLID = 1, OperatorID = 0, Version = 0, XNAME = "中药小类1", ZLID = 1 },
                        new { XLID = 2, OperatorID = 0, Version = 0, XNAME = "中药小类2", ZLID = 1 },
                        new { XLID = 3, OperatorID = 0, Version = 0, XNAME = "中药小类3", ZLID = 2 },
                        new { XLID = 4, OperatorID = 0, Version = 0, XNAME = "中药小类4", ZLID = 2 },
                        new { XLID = 5, OperatorID = 0, Version = 0, XNAME = "西药小类1", ZLID = 3 },
                        new { XLID = 6, OperatorID = 0, Version = 0, XNAME = "西药小类2", ZLID = 3 },
                        new { XLID = 7, OperatorID = 0, Version = 0, XNAME = "西药小类3", ZLID = 4 },
                        new { XLID = 8, OperatorID = 0, Version = 0, XNAME = "西药小类4", ZLID = 4 },
                        new { XLID = 9, OperatorID = 0, Version = 0, XNAME = "其他小类1", ZLID = 5 },
                        new { XLID = 10, OperatorID = 0, Version = 0, XNAME = "其他小类2", ZLID = 5 },
                        new { XLID = 11, OperatorID = 0, Version = 0, XNAME = "其他小类3", ZLID = 6 },
                        new { XLID = 12, OperatorID = 0, Version = 0, XNAME = "其他小类4", ZLID = 6 }
                    );
                });

            modelBuilder.Entity("NewProject.Models.TYMZ", b =>
                {
                    b.Property<int>("ZLID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DLID");

                    b.Property<string>("GUID");

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.Property<string>("ZNAME");

                    b.HasKey("ZLID");

                    b.ToTable("TYMZ");

                    b.HasData(
                        new { ZLID = 1, DLID = 1, OperatorID = 0, Version = 0, ZNAME = "中药中类1" },
                        new { ZLID = 2, DLID = 1, OperatorID = 0, Version = 0, ZNAME = "中药中类2" },
                        new { ZLID = 3, DLID = 2, OperatorID = 0, Version = 0, ZNAME = "西药中类1" },
                        new { ZLID = 4, DLID = 2, OperatorID = 0, Version = 0, ZNAME = "西药中类2" },
                        new { ZLID = 5, DLID = 3, OperatorID = 0, Version = 0, ZNAME = "其他1" },
                        new { ZLID = 6, DLID = 3, OperatorID = 0, Version = 0, ZNAME = "其他2" }
                    );
                });

            modelBuilder.Entity("NewProject.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("Version");

                    b.Property<string>("isDisable");

                    b.Property<string>("user_code")
                        .IsRequired();

                    b.Property<string>("user_explain");

                    b.Property<string>("user_name")
                        .IsRequired();

                    b.Property<string>("user_pwd")
                        .IsRequired();

                    b.Property<string>("zzjg_code");

                    b.HasKey("UserID");

                    b.ToTable("users");

                    b.HasData(
                        new { UserID = 1, OperatorID = 0, Version = 0, isDisable = "0", user_code = "Administrator", user_explain = "系统内置管理员", user_name = "管理员", user_pwd = "123456", zzjg_code = "001" }
                    );
                });

            modelBuilder.Entity("NewProject.Models.UserPowers", b =>
                {
                    b.Property<int>("UserPowersID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperatorID");

                    b.Property<string>("OperatorTime");

                    b.Property<int>("UserID");

                    b.Property<int>("Version");

                    b.Property<int>("powerTeamID");

                    b.HasKey("UserPowersID");

                    b.HasIndex("UserID");

                    b.HasIndex("powerTeamID");

                    b.ToTable("userPowers");

                    b.HasData(
                        new { UserPowersID = 1, OperatorID = 0, UserID = 1, Version = 0, powerTeamID = 1 }
                    );
                });

            modelBuilder.Entity("NewProject.Models.Medicine", b =>
                {
                    b.HasOne("NewProject.Models.TYMD", "TYMD")
                        .WithMany("medicines")
                        .HasForeignKey("DLID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NewProject.Models.TYMLB", "TYMLB")
                        .WithMany("medicines")
                        .HasForeignKey("LBID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NewProject.Models.TYMX", "TYMX")
                        .WithMany("medicines")
                        .HasForeignKey("XLID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NewProject.Models.TYMZ", "TYMZ")
                        .WithMany("medicines")
                        .HasForeignKey("ZLID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NewProject.Models.JGLB", "JGLB")
                        .WithMany("medicines")
                        .HasForeignKey("jglbID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewProject.Models.SPZSJ", b =>
                {
                    b.HasOne("NewProject.Models.Medicine", "medicine")
                        .WithMany("SPZSJ")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewProject.Models.TeamPowers", b =>
                {
                    b.HasOne("NewProject.Models.PowerTeam", "powerTeam")
                        .WithMany("teamPowers")
                        .HasForeignKey("powerTeamID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NewProject.Models.subPowers", "subPowers")
                        .WithMany()
                        .HasForeignKey("subPowerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewProject.Models.UserPowers", b =>
                {
                    b.HasOne("NewProject.Models.User", "user")
                        .WithMany("userPowers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NewProject.Models.PowerTeam", "powerTeam")
                        .WithMany()
                        .HasForeignKey("powerTeamID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
